export interface WordEntry {
  word: string
  hint: string
}

export interface Category {
  id: string
  name: string
  emoji: string
  words: WordEntry[]
}

const w = (word: string, hint: string): WordEntry => ({ word, hint })

export const categories: Category[] = [
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🦁',
    words: [
      w('Elephant', 'It never skips leg day — or forgets your birthday.'),
      w('Penguin', 'Dressed for a gala, lives somewhere freezing.'),
      w('Giraffe', 'Sees over everyone at the concert.'),
      w('Kangaroo', 'Carries its kid in a built-in pocket.'),
      w('Octopus', 'Could high-five four people at once, twice.'),
      w('Dolphin', 'The ocean’s friendliest show-off.'),
      w('Owl', 'Asks "who?" all night long.'),
      w('Zebra', 'Can’t decide between black or white.'),
      w('Shark', 'Its theme song is two notes long.'),
      w('Sloth', 'Would lose a race to a snail on purpose.'),
      w('Flamingo', 'Stands on one leg and rocks pink.'),
      w('Chameleon', 'Changes outfits without moving.'),
      w('Hedgehog', 'A living pincushion that rolls up shy.'),
      w('Panda', 'Eats salad all day and still looks cuddly.'),
      w('Wolf', 'Howls at the moon with the pack.'),
      w('Rabbit', 'Multiplies fast and loves carrots.'),
      w('Crocodile', 'Smiles a lot; you shouldn’t smile back.'),
      w('Bee', 'Works hard, makes something sweet, hates being swatted.'),
      w('Peacock', 'Brings its own fireworks to every party.'),
      w('Camel', 'Packs its own water for the road trip.'),
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    emoji: '🍕',
    words: [
      w('Pizza', 'Arguments start when pineapple gets involved.'),
      w('Sushi', 'Comes with chopsticks and a wasabi warning.'),
      w('Pancakes', 'Stacked high and drowned in syrup.'),
      w('Tacos', 'Tuesday’s favorite dinner.'),
      w('Ice cream', 'Melts faster than your summer plans.'),
      w('Spaghetti', 'Impossible to eat gracefully on a date.'),
      w('Popcorn', 'The official snack of movie night.'),
      w('Burrito', 'A sleeping bag for rice and beans.'),
      w('Croissant', 'Flaky, buttery, and very French.'),
      w('Ramen', 'Slurping it is a compliment.'),
      w('Cheeseburger', 'Fast food royalty between two buns.'),
      w('Waffles', 'Breakfast with a built-in syrup grid.'),
      w('Hot dog', 'A ballpark classic in a bun.'),
      w('Dumplings', 'Little pockets of joy, steamed or fried.'),
      w('Donut', 'The hole is part of the charm.'),
      w('Smoothie', 'Fruit that went through a blender.'),
      w('Nachos', 'The snack everyone reaches into at once.'),
      w('Curry', 'Comes in spice levels from mild to tears.'),
      w('Bubble tea', 'A drink you also have to chew.'),
      w('Fried chicken', 'Crispy outside, finger-licking reputation.'),
    ],
  },
  {
    id: 'places',
    name: 'Places',
    emoji: '🗺️',
    words: [
      w('Beach', 'Sand ends up everywhere for weeks.'),
      w('Airport', 'Hurry up, then wait at the gate.'),
      w('Library', 'Shhh is the house rule.'),
      w('Hospital', 'Everyone here wears gowns or scrubs.'),
      w('Cinema', 'Overpriced snacks, giant screen.'),
      w('Gym', 'Crowded every January.'),
      w('Zoo', 'Please don’t feed the residents.'),
      w('Casino', 'The house always wins here.'),
      w('Desert', 'Bring water. Lots of water.'),
      w('Castle', 'Has a moat and probably a ghost.'),
      w('Subway', 'Mind the gap down here.'),
      w('Farm', 'Wake-up call is a rooster.'),
      w('Space station', 'Your coffee floats if you let go.'),
      w('Waterfall', 'Nature’s loudest shower.'),
      w('Supermarket', 'You came for milk, left with a full cart.'),
      w('School', 'Saved by the bell, literally.'),
      w('Ski resort', 'Hot chocolate tastes best here.'),
      w('Island', 'Surrounded by water on all sides.'),
      w('Museum', 'Look all you want, touch nothing.'),
      w('Campsite', 'Marshmallows meet fire here.'),
    ],
  },
  {
    id: 'sports',
    name: 'Sports & Games',
    emoji: '🏀',
    words: [
      w('Soccer', 'Ninety minutes, one ball, no hands.'),
      w('Chess', 'The queen does all the work.'),
      w('Bowling', 'Rental shoes and a strike of luck.'),
      w('Surfing', 'You spend most of it falling off.'),
      w('Poker', 'Keep your face out of it.'),
      w('Darts', 'Aim small at the pub wall.'),
      w('Golf', 'The lowest score wins, oddly.'),
      w('Yoga', 'Downward dog is not about dogs.'),
      w('Boxing', 'Sting like a bee, wear big gloves.'),
      w('Hide and seek', 'Counting to ten is step one.'),
      w('Skateboarding', 'Concrete plus courage.'),
      w('Tennis', 'Love means zero here.'),
      w('Swimming', 'The only sport where you’re always wet.'),
      w('Archery', 'Robin Hood’s specialty.'),
      w('Rock climbing', 'Chalk up and don’t look down.'),
      w('Ping pong', 'A tiny ball with a big attitude.'),
      w('Fishing', 'Mostly waiting, occasionally reeling.'),
      w('Marathon', 'Twenty-six miles of questioning yourself.'),
      w('Dodgeball', 'The five D’s: dodge, duck, dip, dive, dodge.'),
      w('Karate', 'Belts here aren’t for holding pants up.'),
    ],
  },
  {
    id: 'jobs',
    name: 'Jobs',
    emoji: '🧑‍🚀',
    words: [
      w('Firefighter', 'Runs toward what everyone runs from.'),
      w('Chef', 'Yells "behind!" and owns twenty knives.'),
      w('Astronaut', 'Commutes farther than anyone on Earth.'),
      w('Dentist', 'Asks questions while your mouth is full.'),
      w('Pilot', 'Speaks in a calm voice at 30,000 feet.'),
      w('Barber', 'Small talk included with every visit.'),
      w('Detective', 'Sees clues where you see clutter.'),
      w('Farmer', 'Up before the sun, boots always muddy.'),
      w('Teacher', 'Has eyes in the back of their head.'),
      w('Plumber', 'Saves the day when things go down the drain.'),
      w('Magician', 'Never reveals how it’s done.'),
      w('Lifeguard', 'Paid to sit in the sun and stay alert.'),
      w('Photographer', 'Says "one more" at least five times.'),
      w('Judge', 'Owns a very serious hammer.'),
      w('Electrician', 'Respects the power, literally.'),
      w('Veterinarian', 'Patients bite, bark, or purr.'),
      w('DJ', 'Turns tables without flipping them.'),
      w('Nurse', 'The real boss of the hospital floor.'),
      w('Architect', 'Draws buildings before they exist.'),
      w('Mail carrier', 'Rain or shine, the route gets done.'),
    ],
  },
  {
    id: 'screen',
    name: 'Movies & Shows',
    emoji: '🎬',
    words: [
      w('Titanic', 'There was definitely room on that door.'),
      w('Shrek', 'Ogres have layers, like onions.'),
      w('Frozen', 'The cold never bothered her anyway.'),
      w('Star Wars', 'A long time ago, in a galaxy far away.'),
      w('Harry Potter', 'The boy who lived, with a scar.'),
      w('SpongeBob', 'Lives in a pineapple under the sea.'),
      w('Batman', 'A billionaire with a bat problem.'),
      w('Jurassic Park', 'Life, uh, finds a way.'),
      w('Finding Nemo', 'Just keep swimming.'),
      w('The Simpsons', 'A yellow family from Springfield.'),
      w('Spider-Man', 'Great power, great responsibility.'),
      w('Toy Story', 'They come alive when you leave the room.'),
      w('Stranger Things', 'The Upside Down is not a yoga pose.'),
      w('The Lion King', 'Hakuna matata, circle of life.'),
      w('Minions', 'Small, yellow, obsessed with bananas.'),
      w('Pirates of the Caribbean', 'Why is the rum always gone?'),
      w('Home Alone', 'A kid, two burglars, many traps.'),
      w('Squid Game', 'Red light, green light — for very high stakes.'),
      w('Avatar', 'Big blue people on a glowing planet.'),
      w('E.T.', 'Just wants to phone home.'),
    ],
  },
  {
    id: 'music',
    name: 'Music',
    emoji: '🎵',
    words: [
      w('Guitar', 'Six strings and a campfire reputation.'),
      w('Piano', 'Eighty-eight keys, none open doors.'),
      w('Drums', 'The neighbors’ least favorite instrument.'),
      w('Violin', 'Held between chin and shoulder.'),
      w('Opera', 'Singing so big it needs no microphone.'),
      w('Karaoke', 'Confidence matters more than talent.'),
      w('Trumpet', 'Three buttons, a lot of lung.'),
      w('Choir', 'Many voices, one sound.'),
      w('Bagpipes', 'Scotland’s loudest export.'),
      w('Jazz', 'The wrong notes, played right.'),
      w('Headphones', 'A concert only you can hear.'),
      w('Concert', 'Overpriced tickets, unforgettable night.'),
      w('Vinyl record', 'Music with a satisfying crackle.'),
      w('Saxophone', 'The smoothest sound in the band.'),
      w('Ukulele', 'A guitar that shrunk in the wash.'),
      w('Beatboxing', 'A drum kit made of mouth sounds.'),
      w('Orchestra', 'Dozens of players, one person waving a stick.'),
      w('Microphone', 'Drop it only for dramatic effect.'),
      w('DJ set', 'One person, two turntables, a full dance floor.'),
      w('Lullaby', 'A song designed to end the party.'),
    ],
  },
  {
    id: 'house',
    name: 'Around the House',
    emoji: '🛋️',
    words: [
      w('Toaster', 'Turns bread slightly more exciting.'),
      w('Umbrella', 'Only remembered when it’s too late.'),
      w('Pillow', 'The main event of every fort.'),
      w('Mirror', 'Always copies you exactly.'),
      w('Vacuum cleaner', 'The cat’s sworn enemy.'),
      w('Remote control', 'Always lost between the cushions.'),
      w('Toothbrush', 'Used twice a day, replaced too rarely.'),
      w('Fridge', 'Opened out of boredom, not hunger.'),
      w('Washing machine', 'Where socks go to disappear.'),
      w('Ladder', 'Unlucky to walk under, handy to climb.'),
      w('Scissors', 'Never run while holding these.'),
      w('Candle', 'Makes a blackout feel romantic.'),
      w('Alarm clock', 'The villain of every morning.'),
      w('Doormat', 'The first thing guests step on.'),
      w('Kettle', 'Screams when it’s ready.'),
      w('Bathtub', 'A tiny private swimming pool.'),
      w('Curtains', 'They decide when morning starts.'),
      w('Blender', 'Loud, briefly, then smoothie.'),
      w('Broom', 'A witch’s ride, your chore.'),
      w('Houseplant', 'Survives on neglect and apologies.'),
    ],
  },
]

export function getCategory(id: string): Category | undefined {
  return categories.find((c) => c.id === id)
}
