export interface WordEntry {
  word: string
  hint: string
}

export interface Category {
  id: string
  name: string
  emoji: string
  words: WordEntry[]
}

const w = (word: string, hint: string): WordEntry => ({ word, hint })

// Hints are deliberately vague: they should let the imposter bluff a
// plausible clue, not let them guess the word outright.
export const categories: Category[] = [
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🦁',
    words: [
      w('Elephant', 'Bigger than you.'),
      w('Penguin', 'Not a strong flyer.'),
      w('Giraffe', 'You’d spot it from far away.'),
      w('Kangaroo', 'Quick on its feet.'),
      w('Octopus', 'At home in the water.'),
      w('Dolphin', 'Smarter than it looks.'),
      w('Owl', 'More active at night.'),
      w('Zebra', 'Hard to miss in a crowd.'),
      w('Shark', 'Better admired from a distance.'),
      w('Sloth', 'Never in a hurry.'),
      w('Flamingo', 'Quite the look.'),
      w('Chameleon', 'Easy to overlook.'),
      w('Hedgehog', 'Careful how you pick it up.'),
      w('Panda', 'A picky eater.'),
      w('Wolf', 'Rarely alone.'),
      w('Rabbit', 'Could be a pet.'),
      w('Crocodile', 'Keep your distance.'),
      w('Bee', 'Small but busy.'),
      w('Peacock', 'Likes to be noticed.'),
      w('Camel', 'Built for tough trips.'),
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    emoji: '🍕',
    words: [
      w('Pizza', 'Good for sharing.'),
      w('Sushi', 'Best eaten fresh.'),
      w('Pancakes', 'Usually eaten early in the day.'),
      w('Tacos', 'Eaten with your hands.'),
      w('Ice cream', 'Better in summer.'),
      w('Spaghetti', 'Easy to make a mess with.'),
      w('Popcorn', 'A snack, not a meal.'),
      w('Burrito', 'Very filling.'),
      w('Croissant', 'Goes well with coffee.'),
      w('Ramen', 'Served hot.'),
      w('Cheeseburger', 'You don’t need cutlery.'),
      w('Waffles', 'Usually on the sweet side.'),
      w('Hot dog', 'Common at street stands.'),
      w('Dumplings', 'Comes in batches.'),
      w('Donut', 'A treat, not a meal.'),
      w('Smoothie', 'You drink it.'),
      w('Nachos', 'Crunchy.'),
      w('Curry', 'Can be spicy.'),
      w('Bubble tea', 'A trendy order.'),
      w('Fried chicken', 'Crispy outside.'),
    ],
  },
  {
    id: 'places',
    name: 'Places',
    emoji: '🗺️',
    words: [
      w('Beach', 'Popular in summer.'),
      w('Airport', 'People come and go.'),
      w('Library', 'Keep your voice down.'),
      w('Hospital', 'You hope not to stay long.'),
      w('Cinema', 'Better in the evening.'),
      w('Gym', 'You leave tired.'),
      w('Zoo', 'Fun for kids.'),
      w('Casino', 'Bring money.'),
      w('Desert', 'Not much around.'),
      w('Castle', 'It’s been there a while.'),
      w('Subway', 'Part of many commutes.'),
      w('Farm', 'Early mornings here.'),
      w('Space station', 'Very hard to get to.'),
      w('Waterfall', 'You’ll hear it before you see it.'),
      w('Supermarket', 'You were probably there this week.'),
      w('School', 'Quiet on weekends.'),
      w('Ski resort', 'A seasonal destination.'),
      w('Island', 'Takes some effort to reach.'),
      w('Museum', 'Take your time here.'),
      w('Campsite', 'Pack accordingly.'),
    ],
  },
  {
    id: 'sports',
    name: 'Sports & Games',
    emoji: '🏀',
    words: [
      w('Soccer', 'A team effort.'),
      w('Chess', 'Quiet concentration.'),
      w('Bowling', 'Usually played indoors.'),
      w('Surfing', 'Depends on the weather.'),
      w('Poker', 'Don’t give anything away.'),
      w('Darts', 'Steady hands help.'),
      w('Golf', 'Takes all afternoon.'),
      w('Yoga', 'Wear something comfortable.'),
      w('Boxing', 'Not a team sport.'),
      w('Hide and seek', 'No equipment needed.'),
      w('Skateboarding', 'Expect some bruises.'),
      w('Tennis', 'Back and forth.'),
      w('Swimming', 'Bring a change of clothes.'),
      w('Archery', 'Focus helps.'),
      w('Rock climbing', 'A good grip helps.'),
      w('Ping pong', 'Quick reflexes help.'),
      w('Fishing', 'Patience required.'),
      w('Marathon', 'Pace yourself.'),
      w('Dodgeball', 'Stay alert.'),
      w('Karate', 'Takes discipline.'),
    ],
  },
  {
    id: 'jobs',
    name: 'Jobs',
    emoji: '🧑‍🚀',
    words: [
      w('Firefighter', 'Always on call.'),
      w('Chef', 'Busy in the evenings.'),
      w('Astronaut', 'Years of training.'),
      w('Dentist', 'You book an appointment.'),
      w('Pilot', 'Travels for work.'),
      w('Barber', 'You sit, they work.'),
      w('Detective', 'Asks a lot of questions.'),
      w('Farmer', 'Works outdoors.'),
      w('Teacher', 'Busy on weekdays.'),
      w('Plumber', 'Comes to your place.'),
      w('Magician', 'Works a crowd.'),
      w('Lifeguard', 'A seasonal job.'),
      w('Photographer', 'An eye for detail.'),
      w('Judge', 'Commands respect.'),
      w('Electrician', 'Not a job for amateurs.'),
      w('Veterinarian', 'The patients can’t explain the problem.'),
      w('DJ', 'Works late nights.'),
      w('Nurse', 'Long shifts.'),
      w('Architect', 'Plans ahead.'),
      w('Mail carrier', 'Out in every weather.'),
    ],
  },
  {
    id: 'screen',
    name: 'Movies & Shows',
    emoji: '🎬',
    words: [
      w('Titanic', 'Not a comedy.'),
      w('Shrek', 'Animated.'),
      w('Frozen', 'Kids know every line.'),
      w('Star Wars', 'Part of a big franchise.'),
      w('Harry Potter', 'Based on books.'),
      w('SpongeBob', 'A cartoon.'),
      w('Batman', 'Many versions exist.'),
      w('Jurassic Park', 'A summer blockbuster.'),
      w('Finding Nemo', 'Family-friendly.'),
      w('The Simpsons', 'Been running for ages.'),
      w('Spider-Man', 'Started as a comic.'),
      w('Toy Story', 'Has several sequels.'),
      w('Stranger Things', 'A series, not a film.'),
      w('The Lion King', 'There’s a musical too.'),
      w('Minions', 'Spun off from another film.'),
      w('Pirates of the Caribbean', 'A whole franchise.'),
      w('Home Alone', 'A holiday favorite.'),
      w('Squid Game', 'Not made in Hollywood.'),
      w('Avatar', 'A box-office giant.'),
      w('E.T.', 'An older classic.'),
    ],
  },
  {
    id: 'music',
    name: 'Music',
    emoji: '🎵',
    words: [
      w('Guitar', 'You could bring it to a party.'),
      w('Piano', 'Hard to move.'),
      w('Drums', 'The neighbors have opinions.'),
      w('Violin', 'Common in orchestras.'),
      w('Opera', 'People dress up for it.'),
      w('Karaoke', 'Anyone can join in.'),
      w('Trumpet', 'Takes a lot of air.'),
      w('Choir', 'A group activity.'),
      w('Bagpipes', 'An acquired taste.'),
      w('Jazz', 'Best experienced live.'),
      w('Headphones', 'Not an instrument.'),
      w('Concert', 'Buy tickets early.'),
      w('Vinyl record', 'Making a comeback.'),
      w('Saxophone', 'Smooth.'),
      w('Ukulele', 'Beginner-friendly.'),
      w('Beatboxing', 'No equipment needed.'),
      w('Orchestra', 'Lots of people involved.'),
      w('Microphone', 'Speak up.'),
      w('DJ set', 'Keeps the night going.'),
      w('Lullaby', 'Keep it soft.'),
    ],
  },
  {
    id: 'house',
    name: 'Around the House',
    emoji: '🛋️',
    words: [
      w('Toaster', 'Lives in the kitchen.'),
      w('Umbrella', 'Weather-dependent.'),
      w('Pillow', 'Soft.'),
      w('Mirror', 'Fragile.'),
      w('Vacuum cleaner', 'Loud when in use.'),
      w('Remote control', 'Small and easy to lose.'),
      w('Toothbrush', 'Used daily.'),
      w('Fridge', 'Runs day and night.'),
      w('Washing machine', 'Part of a weekly chore.'),
      w('Ladder', 'Only comes out occasionally.'),
      w('Scissors', 'Handle with care.'),
      w('Candle', 'Nice in the evening.'),
      w('Alarm clock', 'A bedroom item.'),
      w('Doormat', 'Easy to overlook.'),
      w('Kettle', 'Gets hot.'),
      w('Bathtub', 'Not in every home.'),
      w('Curtains', 'Comes in many colors.'),
      w('Blender', 'Loud, but only briefly.'),
      w('Broom', 'For chores.'),
      w('Houseplant', 'Needs occasional attention.'),
    ],
  },
]

export function getCategory(id: string): Category | undefined {
  return categories.find((c) => c.id === id)
}
